# This is a basic workflow to help you get started with Actions
name: Simple_workflow

on: workflow_dispatch

jobs:
  myfistjob:
   runs-on: ubuntu-latest
   steps:
      - name: print greeting
        run: echo "This is my first job"

      - name: closing now
        run: echo "closing now"
